<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_QTYDESCRIPTIONContinue ShoppingCheckout</name>
   <tag></tag>
   <elementGuidId>a85b75f9-b28b-42ca-bb1e-b81ac52cda5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cart_contents_container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cart_contents_container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e47a7e80-623a-4388-8f83-ed5471946ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart_contents_container</value>
      <webElementGuid>07756361-5059-448b-9a94-0260cc823862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart_contents_container</value>
      <webElementGuid>3fad1547-8b7c-430a-98fb-39e6d7bf1a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QTYDESCRIPTIONContinue ShoppingCheckout</value>
      <webElementGuid>6c01ffd3-d535-44b1-bca9-cdbd293c7462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart_contents_container&quot;)</value>
      <webElementGuid>e9bd21c1-4b56-45d7-9072-100f13a02f3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cart_contents_container']</value>
      <webElementGuid>a5c44e0f-a27a-4fd5-a82a-0feb09ad7631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contents_wrapper']/div[2]</value>
      <webElementGuid>4a8c624a-7c53-433c-adc6-2954ab25c706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Cart'])[1]/following::div[1]</value>
      <webElementGuid>73176585-5661-4c87-bb61-7b2bd113de32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close Menu'])[1]/following::div[5]</value>
      <webElementGuid>0160bbff-551d-437c-894b-557f918ef4a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>3096a293-b3de-4455-a08f-f226a36f6f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cart_contents_container' and (text() = 'QTYDESCRIPTIONContinue ShoppingCheckout' or . = 'QTYDESCRIPTIONContinue ShoppingCheckout')]</value>
      <webElementGuid>d4558dc0-b84f-4534-9480-d9ba259568c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
